spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tmp/${db.name};DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      #none, validate, update, create, create-drop
      ddl-auto: none
    show-sql: true
  dbunit:
    operationType: CLEAN_INSERT
    sample-file: src/test/resources/sample-data.xml
    data-factory: org.dbunit.ext.h2.H2DataTypeFactory
  main:
    allow-bean-definition-overriding: true

  redis:
    port: 6379
    host: localhost
    timeout: 60s


db:
  name: develop_boot_sample

server:
  port: 8080

logging:
  level:
    vip.codemonkey: DEBUG


codemonkey:
    security:
      normal:
        loginType: JSON
      validate-code:
               image:
                 length: 6
                 width: 100